### ISSUE TITLE
Hello docbull, allow me to be presumptuous

### ISSUE THREAD

**Issue by xinyoulinxi-T** [docbull/docbull#1]
In fact, I want to ask you a few questions, I see that you have done a lot in libp2p and HLF, I have been working on it recently, but I have encountered problems, I want to consult you to join gossipsub in HLF but did not develop it later, is it because of poor performance efficiency? I hope you can answer my doubts, thank you very much

**Comment by docbull** [comment]
> In fact, I want to ask you a few questions, I see that you have done a lot in libp2p and HLF, I have been working on it recently, but I have encountered problems, I want to consult you to join gossipsub in HLF but did not develop it later, is it because of poor performance efficiency? I hope you can answer my doubts, thank you very much

Hi, xinyoulinxi-T.

As a graduate student and a researcher in distributed system lab at the university, I joined lots of HLF-based blockchain projects and studied libp2p protocol.

As you know HLF uses gossip protocol that is implemented in pubsub for disseminating blocks.
When the gossip protocol runs, the peers randomly select other peers (3 peers as default), which may degrade performance such as wasting network resources by receiving duplicate blocks. (You can see the codes in https://github.com/hyperledger/fabric/blob/main/gossip/filter/filter.go)

By the way, this is not why I don't develop HLF and libp2p recently, I'm just on the other work.

Thank you for asking me.

**Comment by xinyoulinxi-T** [comment]
Okay, but actually, I didn't use gossipsub when running your hlf+gossipsub, how do I use it

**Comment by xinyoulinxi-T** [comment]
Thank you very much for your response to me in your busy schedule

**Comment by docbull** [comment]
I'm sorry that I didn't recognize you meant this project (https://github.com/docbull/hyperledger-fabric-gossipsub).

Well, this project was stopped because I suddenly joined another project when I'm working on it, so I don't know how to make it work and I cannot help you as you wish. 🥲

These are the only tips I can give you: 
   You can change the peers' block dissemination by editing these codes
      https://github.com/docbull/hyperledger-fabric-gossipsub/blob/main/gossip/comm/comm_impl.go
      https://github.com/docbull/hyperledger-fabric-gossipsub/blob/main/gossip/comm/conn.go

   Sending block data codes are implemented in comm_impl.go.
   If you want to see how they send blocks, check the sendToEndpoint() function.

   receiving block codes are implemented in readFromStream.
   receiving and processing flows are implemented in readFromStream()

I wish this may help you.

I'm so sorry that I provided not working repository.

**Comment by xinyoulinxi-T** [comment]
Ok, I see, thanks for the answer
